# Generated by Django 3.2.13 on 2022-07-04 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about',
            new_name='team',
        ),
    ]
